plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/exec"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/git"
  - "@semantic-release/github"
branches:
  - "master"
  - "main"
# - "+([0-9])?(.{+([0-9]),x}).x"
# - name: "alpha"
  # prerelease: "alpha"