- name: Deploy common
  hosts: all

  roles:
    # - bihealth.python3
    - ohmyzsh
    # - cloudalchemy.node-exporter
    # - netdata
    - common
  become: true

  tasks:
    # - name: Ensure python Ansible Requirements modules.
    #   pip:
    #     name:
    #       - PyYAML
    #       - ansible-lint
    #       - cryptography
    #       - gevent
    #       - grpcio
    #       - grpcio-tools
    #       - lxml
    #       - passlib
    #       - python-apt
    #       - requests
    #     executable: pip3
    #     state: present
    #   when: ansible_architecture == "x86_64"

    - name: Create a 4096-bit SSH key for user root
      user:
          name: root
          generate_ssh_key: yes
          ssh_key_bits: 4096
          ssh_key_file: .ssh/id_rsa
          
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
      when: ansible_memory_mb['real']['total'] | int >= 16384 or ansible_architecture == "aarch64"

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0 and ansible_memory_mb['real']['total'] | int >= 16384  or ansible_architecture == "aarch64"

    - name : list users to apply oh-my-zsh
      shell: "getent passwd | awk -F: '$3 > 999 {print $1}'"
      register: users

    - name: Reload Font cache
      shell: fc-cache -fv
      when: ansible_architecture == "x86_64" 