- name: Run common
  import_playbook: common.yml

- name: Deploy Linux DevOps War machine with Ansible
  hosts: devops
  become: true

  # vars:
  # nvm_install_script_version: "0.33.11"
  # nvm_node_version: "4.1.1"
  # nvm_install_globally: ['peerflix']
  # terraform_ver: "0.12.20"

  roles:

  # #- wtanaka.gcloud_sdk
  # - anbox
  # - andrewrothstein.kubectl
  # - andrewrothstein.kubernetes-helm
  # - andrewrothstein.vagrant
  # - anydesk
  # - docker
  # - droidcam
  # - fesaille.gh
  # - gantsign.minikube
  # - geerlingguy.packer
  # - grzegorznowak.nvm_node
  # - ibmcloud
  # - kompose-converter
  # - ngetchell.vscode
  # - rancher2-cli
  # - rke
  ##- capistrano
  ##- rgibert.valve_steam
  #- andrewrothstein.terraform
  #- edge-browser
  #- gnagano.ansible_gitflow
  #- plank
  #- suzuki-shunsuke.git-lfs-ubuntu
  - andrewrothstein.sops
  - aws-vpn-client
  - azure-data-studio
  - azurecli
  - brew
  - cf-terraforming
  - cloud-sql-proxy
  - common-desktop
  - common-devops-desktop
  - istioctlenv
  - k3d
  - k6
  - kops
  - mimirtool
  - powershell
  - stern
  - terraform-docs
  - terraformer
  - terragrunt
  - tfenv
  - tfswitch
  - velero-io
  tasks:
  - name: Config git user
    shell: git config --global color.ui true && git config --global user.email "{{ item }}@{{ ansible_fqdn }}" && git config --global user.name "{{ item }}" && git config --global init.defaultBranch main
    with_items: "{{ users.stdout_lines }}"

  - name: Fix Docker execution without sudo #Issue #7
    shell: "users=$( getent passwd | awk -F: '$3 > 999 {print $1}' );for user in $users; do sudo usermod -a -G docker $user; done"
