---
- name: Run common
  import_playbook: common.yml

- name: Deploy Linux DevOps War machine with Ansible
  hosts: devops
  become: true

  # vars:
    # nvm_install_script_version: "0.33.11"
    # nvm_node_version: "4.1.1"
    # nvm_install_globally: ['peerflix']
    # terraform_ver: "0.12.20"

  roles:
    - common-desktop
    - common-devops-desktop
      #- plank
    - droidcam
      # - anydesk
    #- edge-browser
    - andrewrothstein.vagrant
    - azure-data-studio
    - cloud-sql-proxy
    - tfswitch
    - terragrunt
    - andrewrothstein.sops
    - brew
    #####################
    # - grzegorznowak.nvm_node
    #- andrewrothstein.terraform
    #- suzuki-shunsuke.git-lfs-ubuntu
    #- gnagano.ansible_gitflow
    # - ngetchell.vscode
    ##- capistrano
    ##- rgibert.valve_steam
    # - geerlingguy.packer
    - docker
    # - gantsign.minikube
    # - andrewrothstein.kubectl
    # - rke
    # - andrewrothstein.kubernetes-helm
    # - rancher2-cli
    # - kompose-converter
    # #- wtanaka.gcloud_sdk
    # - ibmcloud
    - azurecli
    - kops
    - k3d
    - tfenv
    - terraformer
    - istioctlenv
    - cf-terraforming
    - velero-io
    - fesaille.gh
    - terraform-docs
    - stern
    - aws-vpn-client
    # - anbox

  tasks:
    - name: Config git user
      shell: git config --global color.ui true && git config --global user.email "{{ item }}@{{ ansible_fqdn }}" && git config --global user.name "{{ item }}" && git config --global init.defaultBranch main
      with_items: "{{ users.stdout_lines }}"

    - name: Fix Docker execution without sudo #Issue #7
      shell: "users=$( getent passwd | awk -F: '$3 > 999 {print $1}' );for user in $users; do sudo usermod -a -G docker $user; done"
