- name: Deploy MAC DevOps Machine with Ansible
  hosts: desktop
  become: false

  vars:
    # ohmyzsh_folders:
    #   - "/usr/local/share/zsh"
    #   - "/usr/local/share/zsh/site-functions"

  roles:
    - common-mac

  tasks:
