- name: Run common on MAC
  import_playbook: mac-common.yml

- name: Deploy MAC Desktop Machine with Ansible
  hosts: mac
  become: false

  vars:
    # ohmyzsh_folders:
    #   - "/usr/local/share/zsh"
    #   - "/usr/local/share/zsh/site-functions"

  roles:
    - common-mac-desktop
    - lmstudio
    - inputleap
    - docker

  tasks:
