- name: Run common on MAC
  import_playbook: mac-common.yml

- name: Deploy MacOS DevOps War machine with Ansible
  hosts: mac
  become: false

  vars:
    # ohmyzsh_folders:
    #   - "/usr/local/share/zsh"
    #   - "/usr/local/share/zsh/site-functions"

  roles:
    # - common-devops-mac

  tasks:
