---
- name: Run common
  import_playbook: common.yml

- name: Deploy pi device with Ansible
  hosts: pi
  become: true

  # vars:

  roles:
    - docker

  tasks:
    - name: Fix Docker execution without sudo #Issue #7
      shell: "users=$( getent passwd | awk -F: '$3 > 999 {print $1}' );for user in $users; do sudo usermod -a -G docker $user; done"