---
- name: Run common
  import_playbook: common.yml

- name: Deploy a server with Ansible
  hosts: server
  become: true

  roles:
    - common-server
    - docker

  tasks:
    - name: Config git user
      shell: git config --global color.ui true && git config --global user.email "{{ item }}@{{ ansible_fqdn }}" && git config --global user.name "{{ item }}" && git config --global init.defaultBranch main
      with_items: "{{ users.stdout_lines }}"

    - name: Fix Docker execution without sudo #Issue #7
      shell: "users=$( getent passwd | awk -F: '$3 > 999 {print $1}' );for user in $users; do sudo usermod -a -G docker $user; done"
