cd /home/${USER}/.config/sublime-text-3 &&
mkdir -p 'Installed Packages' &&
wget https://packagecontrol.io/Package%20Control.sublime-package -P Installed\ Packages

cd /home/${USER}/.config/sublime-text-3/Packages &&

git clone https://bitbucket.org/hmml/jsonlint.git &&
git clone https://github.com/73rhodes/Sublime-JSLint.git &&
git clone https://github.com/adambullmer/sublime_ansible_vault.git &&
git clone https://github.com/ahmedash95/sublime-laravel-blade-autocomplete.git &&
git clone https://github.com/alepez/LiveReload-sublimetext3.git &&
git clone https://github.com/alepez/LiveReloadMake-sublimetext3.git &&
git clone https://github.com/AlexanderEkdahl/github-sublime-theme.git &&
git clone https://github.com/alienhard/SublimeAllAutocomplete.git &&
git clone https://github.com/amit-bansil/TicketMaster.git &&
git clone https://github.com/apiad/sublime-flashback.git &&
git clone https://github.com/arnellebalane/sublime-open-in-git-repository.git &&
git clone https://github.com/asbjornenge/Docker.tmbundle.git &&
git clone https://github.com/aukaost/SublimePrettyYAML.git &&
git clone https://github.com/benmatselby/sublime-jenkins-dashboard.git &&
git clone https://github.com/bgreenlee/sublime-github.git &&
git clone https://github.com/biannetta/MySublimeQL.git &&
git clone https://github.com/bofm/sublime_sqlplus.git &&
git clone https://github.com/cakephp/cakephp-tmbundle.git CakePHP.tmbundle &&
git clone https://github.com/CasperLaiTW/ERBAutocomplete.git &&
git clone https://github.com/cbumgard/GitCommitMsg.git &&
git clone https://github.com/clifford-github/sublime-ansible.git &&
git clone https://github.com/Colorsublime/Colorsublime-Plugin.git &&
git clone https://github.com/CraigWilliams/BeautifyRuby.git &&
git clone https://github.com/DamnWidget/anaconda.git &&
git clone https://github.com/danpe/QuickRails.git &&
git clone https://github.com/devdoc/SublimeLinter-jslint.git &&
git clone https://github.com/divinites/gissues.git &&
git clone https://github.com/domeide/sublime-docker.git &&
git clone https://github.com/dschaaff/SublimeLinter-puppet-lint.git &&
git clone https://github.com/dschaaff/SublimeLinter-puppet.git &&
git clone https://github.com/dydx/Laravel-5-Artisan.git &&
git clone https://github.com/evgeny-golubev/Laravel-4-Artisan.git &&
git clone https://github.com/facelessuser/BracketHighlighter.git &&
git clone https://github.com/facelessuser/SubNotify.git &&
git clone https://github.com/frou/st3-gitblame.git &&
git clone https://github.com/gbaptista/sublime-3-pretty-ruby.git &&
git clone https://github.com/gbaptista/sublime-3-shell-exec.git &&
git clone https://github.com/geekpradd/Flask-Sublime.git  &&
git clone https://github.com/gnarula/sublime-laravelgenerator.git &&
git clone https://github.com/HexRx/simple-ftp-deploy.git &&
git clone https://github.com/jacobmovingfwd/eml-syntax.git &&
git clone https://github.com/jisaacks/GitGutter.git &&
git clone https://github.com/jnordberg/sublime-colorpick.git &&
git clone https://github.com/jobywalker/PgSQL-Sublime.git &&
git clone https://github.com/june07/sublime-Jenkinsfile.git &&
git clone https://github.com/kemayo/sublime-text-git.git &&
git clone https://github.com/kenspirit/MarkdownCodeBlockWrapper.git &&
git clone https://github.com/kevinxucs/Sublime-Gitignore.git &&
git clone https://github.com/korniychuk/sublime-sql-snippets.git &&
git clone https://github.com/Kristories/Sublime-Mongo-PHP.git &&
git clone https://github.com/Lykegenes/laravel-5-snippets.git &&
git clone https://github.com/marceloxp/laravel_migration_snippets.git &&
git clone https://github.com/MattDMo/Neon-color-scheme.git &&
git clone https://github.com/Medalink/laravel-blade.git &&
git clone https://github.com/mliljedahl/SublimeLinter-contrib-ansible-lint.git &&
git clone https://github.com/molovo/sublime-zsh.git &&
git clone https://github.com/Monnoroch/ColorHighlighter.git &&
git clone https://github.com/mpmont/ci-snippets.git &&
git clone https://github.com/mtxr/SublimeText-SQLTools.git &&
git clone https://github.com/patricktalmadge/Bootstrapper_snippets.git &&
git clone https://github.com/philippotto/Sublime-BracketGuard.git &&
git clone https://github.com/predragnikolic/sublime-git-diff-view.git &&
git clone https://github.com/prog1dev/SublimeLinter-contrib-dockerfilelint.git &&
git clone https://github.com/randy3k/GitStatusBar.git &&
git clone https://github.com/RoverWire/codeigniter-utilities.git &&
git clone https://github.com/russCloak/SublimePuppet.git &&
git clone https://github.com/samvasko/laravel4-snippets.git &&
git clone https://github.com/schneidmaster/cap_rails.git &&
git clone https://github.com/seregatte/AnsibleSnippets.git &&
git clone https://github.com/sergeche/emmet-sublime.git &&
git clone https://github.com/SnoringFrog/GitlabIntegrate.git &&
git clone https://github.com/spadgos/sublime-jsdocs.git &&
git clone https://github.com/spectacles/CodeComplice.git &&
git clone https://github.com/SublimeGit/SublimeGit.git &&
git clone https://github.com/SublimeLinter/SublimeLinter-pyyaml.git &&
git clone https://github.com/SublimeLinter/SublimeLinter-ruby.git &&
git clone https://github.com/SublimeLinter/SublimeLinter.git &&
git clone https://github.com/SublimeText/Rake.git &&
git clone https://github.com/tadast/sublime-rails-snippets.git &&
git clone https://github.com/temochka/sublime-text-2-github-tools.git &&
#git clone https://github.com/tennantje/railsdev-sublime-snippets.git &&
git clone https://github.com/thespacedoctor/fundamentals-Sublime-Snippets.git &&
git clone https://github.com/thomasmeeus/SublimeLinter-contrib-yamllint.git &&
git clone https://github.com/titoBouzout/SideBarEnhancements.git &&
git clone https://github.com/tkopets/sublime-postgresql-syntax.git &&
git clone https://github.com/todorowww/st2-snippet-ci2-mc.git &&
git clone https://github.com/udokmeci/sublime-yii2-autocomplete.git &&
git clone https://github.com/unknownuser88/github-notifications.git &&
git clone https://github.com/vlakarados/gitstatus.git &&
git clone https://github.com/vovkkk/sublime_git_syntaxes.git &&
git clone https://github.com/wbond/sublime_alignment.git &&
git clone https://github.com/wbond/sublime_terminal.git &&
git clone https://github.com/webchun/bootstrap-3-sublime-autocomplete.git &&
git clone https://github.com/webchun/bootstrap-4-sublime-autocomplete.git &&
git clone https://github.com/weslly/ColorPicker.git &&
git clone https://github.com/witsec/SublimeLinter-contrib-yaml-lint.git &&
git clone https://github.com/wuub/SublimeREPL.git &&
git clone https://github.com/xiewandongqq/subversion_for_sublime_txt3.git &&
git clone https://github.com/xr1337/sublime-kubernetes-autocomplete.git &&
git clone https://github.com/Zeeker/sublime-GitConflictResolver.git &&
git clone https://github.com/math2001/MarkdownLivePreview.git &&
git clone https://github.com/braver/MarkdownHighlighting.git &&
git clone https://github.com/jonschlinkert/sublime-markdown-extended.git &&
git clone https://github.com/memoryleak/TerraformSnippets-AWS.git TerraformSnippets-AWS &&
git clone https://github.com/alexlouden/Terraform.tmLanguage.git &&
git clone https://github.com/p3lim/sublime-terrafmt Terrafmt

