collections:
- ansible.posix
- community.docker
# - community.general
- community.sops
- kubernetes.core

- name: community.general
  version: 6.0.0

roles:
- name: common-mac
  src: https://github.com/hackwish/ansible-common-mac.git

- name: common-mac-desktop
  src: https://github.com/hackwish/ansible-common-mac-desktop.git

- name: common-mac-devops-desktop
  src: https://github.com/hackwish/ansible-common-mac-devops-desktop.git

- name: lmstudio
  src: https://github.com/hackwish/ansible-lmstudio.git

- name: inputleap
  src: https://github.com/hackwish/ansible-inputleap.git

- name: docker
  src: https://github.com/hackwish/ansible-docker.git